### ISSUE TITLE
API discrepancy between hash_grow and hash_nogrow

### ISSUE THREAD

**Issue by skadic** [cmuparlay/parlayhash#1]
Hello,

when trying to use parlayhash, I came across a discrepancy in the API between the growing and non-growing map implementation.
Specifically this is about the `upsert` function. As the readme suggests, the signature should be: `upsert(const K&, (const std::optional<V>&) -> V)) -> bool`, taking a key and an update function as parameters.
For `hash_nogrow`, this is the case: ([link](https://github.com/cmuparlay/parlayhash/blob/dda80fcb90fb6f8ff5b5a7a730b202a7ceca6200/include/hash_nogrow/unordered_map.h#L360C3-L366C4))
```cpp
template <typename F>
bool upsert(const K& k, const F& f) {
  ...
}
```
However for `hash_grow`, the signature is different (`upsert(const K&, const V&) -> bool`), instead taking a key and a value as parameters: ([link](https://github.com/cmuparlay/parlayhash/blob/dda80fcb90fb6f8ff5b5a7a730b202a7ceca6200/include/hash_grow/unordered_map.h#L559C3-L568C4))
```cpp
bool upsert(const K& k, const V& v) {
  ...
}
```
This also does not seem to be fixed by simply adjusting the signature in `hash_grow` to match the one in `hash_nogrow` as this leads to further compiler errors.

For a minimal reproduction of this issue, see the `nogrow_upsert` and `grow_upsert` targets in this repo: https://github.com/Skadic/parlay_issues
Both targets use the same code, but use the non-growing or growing hash tables respectively.
The former will compile as expected, the latter will not.

Thank you

**Comment by gblelloch** [comment]
Thanks for reporting the issues.   I should note that the grow version of
the hash table is work in progress.

Guy

**Comment by gblelloch** [comment]
Fixed the issue.   The interfaces are now consistent.   Also added more tests (both in tests and benchmarks), and the growable hash table is passing all of them.
