### ISSUE TITLE
corrupted head/corrupted tail

### ISSUE THREAD

**Issue by skadic** [cmuparlay/parlayhash#2]
Hello,

when using `hash_nogrow`, I'm encountering `corrupted head`/`corrupted tail` errors.
A minimal reproduction of this issue is this code snippet:
```cpp
#include <hash_nogrow/unordered_map.h>

#define NUM_ITERS 1000000

int main() {
    parlay::unordered_map<int, int> map(NUM_ITERS);
    for (int i = 0; i < NUM_ITERS; i++) {
        map.insert(i, i);
    }

    // Upsert all values once
    for (int i = 0; i < NUM_ITERS; i++) {
        map.upsert(i, [i](std::optional<int> v) -> int {
            if (v) {
                return 2 * i;
            } else {
                return -i;
            }
        });
    }
}
```
If built in Debug, or RelwithDebInfo mode, this will terminate with "corrupted head"/"corrupted tail" errors.
The target `nogrow_corrupt` in this repo corresponds to this example: https://github.com/Skadic/parlay_issues.

**Comment by gblelloch** [comment]
Thanks for this report.   We will look into it.

**Comment by gblelloch** [comment]
The problem is fixed.   Was allocating wrong sized structure for upsert.
