### ISSUE TITLE
Support for `clear()` functionality

### ISSUE THREAD

**Issue by jamshed** [cmuparlay/parlayhash#5]
Hi,

Thanks for this really cool and performant library! I was wondering, if you may have any plans to add the `clear()` functionality to the map (which need not necessarily change the capacity)? A `clear()` interface would be very helpful in my use-case, and it could be a quite useful feature in general.

Thank you!

**Comment by gblelloch** [comment]
The parlayhash repository has a new implementation of parlay_hash.   It
includes a clear() function.   Note that the function names have changed
from find, insert, remove to Find, Insert, Remove.   There are also new
"find", "remove" and "erase" functions, that largely match the
std::unordered_map interface.

Guy
