### ISSUE TITLE
Please make a release of the current version

### ISSUE THREAD

**Issue by fpelliccioni** [cmuparlay/parlayhash#6]
The latest version (0.0.2) has a different directory structure than the one in master/main branch:

```
include/
    hash_grow/
    hash_nogrow/
    parlay/
```    
versus:

```
include/
    parlay_hash/
    parlay/
    ...
```    

I am creating a Conan (package manager) recipe for Parlay Hash and I would like to use the latest directory structure.

Thanks

**Comment by gblelloch** [comment]
Not sure what you mean by the latest version?   We did a major reorganization of the directory structure and the implementation that was added a couple weeks ago to the main branch.    Now there is only one implementation, which is in "include/parlay_hash" (which allows for growing).   There are no longer separate hash_grow and hash_nogrow implementations since we found the growable version was effectively just as fast as the no_grow version.  The new implementation is also faster by about 25%.

Sorry if this conflicted with your work on a Conan recipe.

**Comment by fpelliccioni** [comment]
> Not sure what you mean by the latest version? We did a major reorganization of the directory structure and the implementation that was added a couple weeks ago to the main branch. Now there is only one implementation, which is in "include/parlay_hash" (which allows for growing). There are no longer separate hash_grow and hash_nogrow implementations since we found the growable version was effectively just as fast as the no_grow version. The new implementation is also faster by about 25%.
> 
> Sorry if this conflicted with your work on a Conan recipe.

@gblelloch 

Thank you for your prompt response and for the update on the reorganization of the directory structure in the main branch. I understand that the new implementation combines the features of the previous versions and is more efficient, which is great news.

I wanted to clarify that there's no issue at all regarding the changes impacting the Conan recipe I'm working on. The flexibility of package management with Conan allows for easy adaptation to such changes.

However, for Conan to effectively manage the Parlay Hash package, it requires the ability to download code from specific tags or releases on GitHub. Currently, the latest release (0.0.2) still contains the old directory structure. My request is, could you please create a new release on GitHub that reflects the latest directory structure and implementation?

Having a release that corresponds with the current main branch's structure is crucial for maintaining consistency. Once a new release is available, I can ensure that the first Conan package for Parlay Hash aligns with your latest and most efficient implementation. This will also prevent any compatibility issues for users who rely on the Conan repository when the new version is released.

I appreciate your consideration of this request and look forward to the continued success of the Parlay Hash project.

**Comment by gblelloch** [comment]
OK, thanks for the clarification.    Done.
